# Generated by Django 3.2.7 on 2021-09-06 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentiment', models.CharField(max_length=100)),
                ('tag', models.CharField(max_length=100)),
                ('word', models.TextField(max_length=100)),
                ('count', models.IntegerField()),
            ],
        ),
    ]
